Refactor `dplyr` functions used.
daattali/ddpcr pull request #27
Opened 2024-03-08 12:45 UTC by paulduf

Switching from `select_`, `filter_`, `arrange_`, `group_by_` , `mutate_`, `rename_` to the now-default, without-trailing-underscore versions. This basically boils down to removing formulas as arguments.

I also import `dplyr`'s `all_of`, `one_of` and `any_of` and added `all_of` in some places where select is given a character vector, this is safer (errors if one column entry is missing in the dataframe).

All tests now pass without warnings.

2024-03-08 16:57 UTC, daattali commented
I'm not up to date with dplyr/tidyverse best practices, but back when I created this package, writing `dplyr::filter(well == well_id)` was considered bad practice in packages. It was fine for doing interactive analysis or in personal scripts, but when coding in a package, it was always advised to avoid using NSE. That's why I used `filter_(~ ...)` even when the alternative would have worked.

I understand that `filter_` is now deprecated, but I would prefer to still avoid NSE where possible. Are you familiar with this?

2024-03-08 17:58 UTC, paulduf commented
> I understand that `filter_` is now deprecated, but I would prefer to still avoid NSE where possible. Are you familiar with this?

I am not TBH but I can find out more. I am (part-time) programming in R for ca. 2 years now and mostly used to this syntax. Do you have an example why the formula is preferred over the NSE syntax ? I am interested in a failure mode of NSE here.

2024-03-11 14:55 UTC, daattali commented
Non standard evaluation blurs the line between variables and strings. It's absolutely great for interactive use, but when programming you always want to be as explicit as possible so that debugging is easier and so that you can reason about the code with more certainty. Imagine I do `cyl <- "gear"; dplyr::filter(mtcars, cyl == 4)` - it's not immediately clear whether it will filter the `gear` or the `cyl` column, because `cyl` is being used as if it's a regular variable, but it will not be treated as a variable - it'll be treated in a NSE way. I'm sure many people have discussed this in the past, [Hadley's book has a very short section on it](http://adv-r.had.co.nz/Computing-on-the-language.html#nse-downsides) but for more in depth analysis you can ask on an online forum

2024-03-20 15:48 UTC, paulduf commented
I found that using the `.data` pronoun in dplyr functions' arguments is the way to go if we want to avoid NSE.

https://dplyr.tidyverse.org/articles/programming.html
https://www.sesync.org/resources/standardizing-non-standard-evaluation-r

I also encountered [this blogpost](https://www.tidyverse.org/blog/2023/04/performant-packages/) which gives hint how to get rid of dplyr functions for more efficient alternatives, and is also a way to avoid NSE. This should be remembered for critical parts of the code, but I don't feel like implementing this everywhere because it also makes the code less readable and I also spent enough time on this, the main objective being to remove the warnings :).

2024-03-22 20:15 UTC, daattali requested changes
Thanks a lot for all the work!

I made a few requests, most of them are places where you kept/used old style of dplyr syntax. The use of `!!` is outdated, that was used several years ago (this package was written before that, when it was even uglier to write code!), so I just asked that you replace those with the modern dplyr syntax, which is really much much more readable.

I think after all the changes, there should hopefully not be any more uses of the `lazyeval` package, and then it can be removed from the DESCRIPTION

2024-03-22 20:15 UTC, daattali commented on R/plate-utils.R
> +    arrange_meta()
Thanks!

2024-03-22 20:15 UTC, daattali commented on R/plot.R
> +      dplyr::arrange(row, col)
Forgot to fix this one

2024-03-22 20:15 UTC, daattali commented on R/pnpp_experiment-classify.R
> +    dplyr::filter(!!sym(variable_var) <= negative_border)
Same here

2024-03-22 20:15 UTC, daattali commented on R/pnpp_experiment-classify.R
> +    dplyr::filter(!!sym(variable_var) > negative_border)
Same here

2024-03-22 20:15 UTC, daattali commented on R/pnpp_experiment-classify.R
> +          !!sym(variable_var) %btwn% dens_smooth$x[utils::tail(minima_idx, 2)]
I think !!sym(x) can just be replaced with .data[[x]], no?

2024-03-22 20:15 UTC, daattali commented on R/pnpp_experiment-classify.R
> +      dplyr::filter(!!sym(variable_var) <= negative_border)
and again :)

2024-03-22 20:15 UTC, daattali commented on R/pnpp_experiment-classify.R
> +      dplyr::filter(!!sym(variable_var) > negative_border)
last one

2024-03-22 20:15 UTC, daattali commented on R/pnpp_experiment-filled.R
> +    dplyr::filter(!!sym(positive_dim_var(plate)) >= border)
no `!!`

2024-03-22 20:15 UTC, daattali commented on R/type-pnpp_experiment.R
> +    dplyr::filter(!(!!sym(var_name))) %>%
no `!!`

2024-03-22 20:15 UTC, daattali commented on R/type-pnpp_experiment.R
> +    dplyr::filter(!!sym(var_name)) %>%
`!!`

2024-03-22 20:15 UTC, daattali commented on R/utils.R
> +        dplyr::rename(!!colname := all_of(colname_x)) %>%
`"{colname}"`

2024-03-25 16:01 UTC, paulduf commented on R/plate-attribs.R
> +    dplyr::rename(!!value := x_var(plate))
That's right. Not the best to my taste because a linter may not detect that `value` is a variable but still the recommended way to go.

2024-03-25 16:22 UTC, paulduf commented
> Thanks a lot for all the work!
> 
> I made a few requests, most of them are places where you kept/used old style of dplyr syntax. The use of `!!` is outdated, that was used several years ago (this package was written before that, when it was even uglier to write code!), so I just asked that you replace those with the modern dplyr syntax, which is really much much more readable.
> 
> I think after all the changes, there should hopefully not be any more uses of the `lazyeval` package, and then it can be removed from the DESCRIPTION

Thanks for your review, I think I catched them all now.

2024-03-26 06:43 UTC, daattali requested changes
just a few last places where the old code is still used

2024-03-26 06:43 UTC, daattali commented on R/aaa.R
> +  dplyr::select(all_of(c("well", "sample", "row", "col", "used")))
all_of is missing `dplyr::`

2024-03-26 06:43 UTC, daattali commented on R/plate-utils.R
> +        dplyr::select(one_of(meta_cols_keep)) %>%
`one_of` is missing `dplyr::`

2024-03-26 06:43 UTC, daattali commented on R/pnpp_experiment-classify.R
> +          !!sym(variable_var) %btwn% dens_smooth$x[utils::tail(minima_idx, 2)]
this one still needs to be fixed

2024-03-26 06:43 UTC, daattali commented on R/pnpp_experiment-classify.R
> +    dplyr::filter(!!sym(variable_var) <= negative_border)
this sym needs to changed to the current NSE version

2024-03-26 06:43 UTC, daattali commented on R/pnpp_experiment-classify.R
> +    dplyr::filter(!!sym(variable_var) > negative_border)
sym is incorrect

2024-03-26 06:43 UTC, daattali commented on R/pnpp_experiment-classify.R
> +      dplyr::filter(!!sym(variable_var) <= negative_border)
another sym

2024-03-26 06:43 UTC, daattali commented on R/pnpp_experiment-classify.R
> +      dplyr::filter(!!sym(variable_var) > negative_border)
last one

2024-03-26 08:16 UTC, paulduf commented
> just a few last places where the old code is still used

Sorry, I don't get why I did not find these with a global search 🤔

2024-03-26 19:00 UTC, daattali commented
All the checks pass now, thanks for the work!

2024-03-26 19:00 UTC, merged